# Generated by Django 4.2.3 on 2023-08-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='notes',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
