# Generated by Django 4.2.3 on 2023-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auther_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='testyhedcbfiehf'),
        ),
        migrations.AddField(
            model_name='book',
            name='imgae',
            field=models.TextField(default='https://www.chappellegardensra.com/app/uploads/2023/01/book-club-1-2.jpg'),
        ),
        migrations.AddField(
            model_name='book',
            name='number_page',
            field=models.IntegerField(default=100),
        ),
    ]
