# Generated by Django 4.2.3 on 2023-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgroud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default='drama'),
            preserve_default=False,
        ),
    ]
